execute if score usage values matches 1 run scoreboard players remove power values 1
execute if score usage values matches 2 run scoreboard players remove power values 2
execute if score usage values matches 3 run scoreboard players remove power values 3
execute if score usage values matches 4 run scoreboard players remove power values 4
execute if score usage values matches 5.. run scoreboard players remove power values 5

execute if score power values matches ..0 run scoreboard players set power_display values 0
execute if score power values matches 1..239 run scoreboard players set power_display values 1
execute if score power values matches 240..359 run scoreboard players set power_display values 2
execute if score power values matches 360..479 run scoreboard players set power_display values 3
execute if score power values matches 480..599 run scoreboard players set power_display values 4
execute if score power values matches 600..719 run scoreboard players set power_display values 5
execute if score power values matches 720..839 run scoreboard players set power_display values 6
execute if score power values matches 840..959 run scoreboard players set power_display values 7
execute if score power values matches 960..1079 run scoreboard players set power_display values 8
execute if score power values matches 1080..1199 run scoreboard players set power_display values 9
execute if score power values matches 1200..1319 run scoreboard players set power_display values 10
execute if score power values matches 1320..1439 run scoreboard players set power_display values 11
execute if score power values matches 1440..1559 run scoreboard players set power_display values 12
execute if score power values matches 1560..1679 run scoreboard players set power_display values 13
execute if score power values matches 1680..1799 run scoreboard players set power_display values 14
execute if score power values matches 1800..1919 run scoreboard players set power_display values 15
execute if score power values matches 1920..2039 run scoreboard players set power_display values 16
execute if score power values matches 2040..2159 run scoreboard players set power_display values 17
execute if score power values matches 2160..2279 run scoreboard players set power_display values 18
execute if score power values matches 2280..2399 run scoreboard players set power_display values 19
execute if score power values matches 2400..2519 run scoreboard players set power_display values 20
execute if score power values matches 2520..2639 run scoreboard players set power_display values 21
execute if score power values matches 2640..2759 run scoreboard players set power_display values 22
execute if score power values matches 2760..2879 run scoreboard players set power_display values 23
execute if score power values matches 2880..2999 run scoreboard players set power_display values 24
execute if score power values matches 3000..3119 run scoreboard players set power_display values 25
execute if score power values matches 3120..3239 run scoreboard players set power_display values 26
execute if score power values matches 3240..3359 run scoreboard players set power_display values 27
execute if score power values matches 3360..3479 run scoreboard players set power_display values 28
execute if score power values matches 3480..3599 run scoreboard players set power_display values 29
execute if score power values matches 3600..3719 run scoreboard players set power_display values 30
execute if score power values matches 3720..3839 run scoreboard players set power_display values 31
execute if score power values matches 3840..3959 run scoreboard players set power_display values 32
execute if score power values matches 3960..4079 run scoreboard players set power_display values 33
execute if score power values matches 4080..4199 run scoreboard players set power_display values 34
execute if score power values matches 4200..4319 run scoreboard players set power_display values 35
execute if score power values matches 4320..4439 run scoreboard players set power_display values 36
execute if score power values matches 4440..4559 run scoreboard players set power_display values 37
execute if score power values matches 4560..4679 run scoreboard players set power_display values 38
execute if score power values matches 4680..4799 run scoreboard players set power_display values 39
execute if score power values matches 4800..4919 run scoreboard players set power_display values 40
execute if score power values matches 4920..5039 run scoreboard players set power_display values 41
execute if score power values matches 5040..5159 run scoreboard players set power_display values 42
execute if score power values matches 5160..5279 run scoreboard players set power_display values 43
execute if score power values matches 5280..5399 run scoreboard players set power_display values 44
execute if score power values matches 5400..5519 run scoreboard players set power_display values 45
execute if score power values matches 5520..5639 run scoreboard players set power_display values 46
execute if score power values matches 5640..5759 run scoreboard players set power_display values 47
execute if score power values matches 5760..5879 run scoreboard players set power_display values 48
execute if score power values matches 5880..5999 run scoreboard players set power_display values 49
execute if score power values matches 6000..6119 run scoreboard players set power_display values 50
execute if score power values matches 6120..6239 run scoreboard players set power_display values 51
execute if score power values matches 6240..6359 run scoreboard players set power_display values 52
execute if score power values matches 6360..6479 run scoreboard players set power_display values 53
execute if score power values matches 6480..6599 run scoreboard players set power_display values 54
execute if score power values matches 6600..6719 run scoreboard players set power_display values 55
execute if score power values matches 6720..6839 run scoreboard players set power_display values 56
execute if score power values matches 6840..6959 run scoreboard players set power_display values 57
execute if score power values matches 6960..7079 run scoreboard players set power_display values 58
execute if score power values matches 7080..7199 run scoreboard players set power_display values 59
execute if score power values matches 7200..7319 run scoreboard players set power_display values 60
execute if score power values matches 7320..7439 run scoreboard players set power_display values 61
execute if score power values matches 7440..7559 run scoreboard players set power_display values 62
execute if score power values matches 7560..7679 run scoreboard players set power_display values 63
execute if score power values matches 7680..7799 run scoreboard players set power_display values 64
execute if score power values matches 7800..7919 run scoreboard players set power_display values 65
execute if score power values matches 7920..8039 run scoreboard players set power_display values 66
execute if score power values matches 8040..8159 run scoreboard players set power_display values 67
execute if score power values matches 8160..8279 run scoreboard players set power_display values 68
execute if score power values matches 8280..8399 run scoreboard players set power_display values 69
execute if score power values matches 8400..8519 run scoreboard players set power_display values 70
execute if score power values matches 8520..8639 run scoreboard players set power_display values 71
execute if score power values matches 8640..8759 run scoreboard players set power_display values 72
execute if score power values matches 8760..8879 run scoreboard players set power_display values 73
execute if score power values matches 8880..8999 run scoreboard players set power_display values 74
execute if score power values matches 9000..9119 run scoreboard players set power_display values 75
execute if score power values matches 9120..9239 run scoreboard players set power_display values 76
execute if score power values matches 9240..9359 run scoreboard players set power_display values 77
execute if score power values matches 9360..9479 run scoreboard players set power_display values 78
execute if score power values matches 9480..9599 run scoreboard players set power_display values 79
execute if score power values matches 9600..9719 run scoreboard players set power_display values 80
execute if score power values matches 9720..9839 run scoreboard players set power_display values 81
execute if score power values matches 9840..9959 run scoreboard players set power_display values 82
execute if score power values matches 9960..10079 run scoreboard players set power_display values 83
execute if score power values matches 10080..10199 run scoreboard players set power_display values 84
execute if score power values matches 10200..10319 run scoreboard players set power_display values 85
execute if score power values matches 10320..10439 run scoreboard players set power_display values 86
execute if score power values matches 10440..10559 run scoreboard players set power_display values 87
execute if score power values matches 10560..10679 run scoreboard players set power_display values 88
execute if score power values matches 10680..10799 run scoreboard players set power_display values 89
execute if score power values matches 10800..10919 run scoreboard players set power_display values 90
execute if score power values matches 10920..11039 run scoreboard players set power_display values 91
execute if score power values matches 11040..11159 run scoreboard players set power_display values 92
execute if score power values matches 11160..11279 run scoreboard players set power_display values 93
execute if score power values matches 11280..11399 run scoreboard players set power_display values 94
execute if score power values matches 11400..11519 run scoreboard players set power_display values 95
execute if score power values matches 11520..11639 run scoreboard players set power_display values 96
execute if score power values matches 11640..11759 run scoreboard players set power_display values 97
execute if score power values matches 11760..11879 run scoreboard players set power_display values 98
execute if score power values matches 11880..11999 run scoreboard players set power_display values 99
execute if score power values matches 12000..12119 run scoreboard players set power_display values 100